--create the database
create database VMOBILE

--create table with all 3 mobile operators
create table CombinedSubscribers (
	Subscriber_ID int identity(1,1) primary key,
	First_Name varchar(100),
	Last_Name varchar(100),
	Cell_Phone_Number varchar(20),
	Date_Of_Birth date,
	[Location] varchar(100),
	SIM_Activation_Date date,
	Source_System_Name varchar(100),
	Is_Master_Record BIT
)
GO

--insert data from all tables into the new table created
insert into CombinedSubscribers(
	First_Name,
	Last_Name,
	Cell_Phone_Number,
	Date_Of_Birth,
	[Location],
	SIM_Activation_Date,
	Source_System_Name,
	Is_Master_Record
)
select
	First_Name,
	Last_Name,
	"Cell_Number" as Cell_Phone_Number,
	"Birthday" as Date_Of_Birth,
	[Location],
	SIM_Activation_Date,
	'VMobile' as Source_System_Name,
	1 as Is_Master_Record --Business rule 1: flagging vmobile as the master source
from [VMOBILE].[dbo].[VMobile_subscribers]
union all
select
	"FirstName" as First_Name,
	"LastName" as Last_Name,
	"CellNo" as Cell_Phone_Number,
	null as Date_Of_Birth,
	"Area" as[Location],
	"SIMDate" as SIM_Activation_Date,
	'ArrowMobile' as Source_System_Name,
	0 as Is_Master_Record
from [VMOBILE].[dbo].[VMobile_subscribers_arrowmobile]
union all
select
	"Name" as First_Name,
	"Surname" as Last_Name,
	"Cell" as Cell_Phone_Number,
	"Date" as Date_Of_Birth,
	"City" as [Location],
	"Activate" as SIM_Activation_Date,
	'BlueMobile' as Source_System_Name,
	0 as Is_Master_Record
from [VMOBILE].[dbo].[VMobile_subscribers_bluemobile]
GO

--Business rule 2: 
--finds duplicate subscribers from arrowmobile and bluemobile
--flag latest sim activation date with 1
with DuplicateSubscribers as (
	select
		Cell_Phone_Number
	from
		CombinedSubscribers
	where
		Source_System_Name in ('ArrowMobile', 'BlueMobile')
	Group by
		Cell_Phone_Number
	having
		count(Cell_Phone_Number) > 1
),RankedDuplicates as (
	select
		cs.Subscriber_ID,
		cs.Cell_Phone_Number,
		ROW_NUMBER() over(partition by cs.Cell_Phone_Number order by cs.SIM_Activation_Date desc) as rn
	from
		CombinedSubscribers as cs
		join
		DuplicateSubscribers as ds on cs.Cell_Phone_Number = ds.Cell_Phone_Number
)
update CombinedSubscribers
set Is_Master_Record = 1
from CombinedSubscribers as u
join RankedDuplicates as r on u.Subscriber_ID = r.Subscriber_ID
where r.rn =1

---------------------------END-------------------------------------


-----------------------SOLUTION-----------------------------------

---1.Reports
--returns table showing names of subscribers, total rev generated by each, sms's, voicecalls/subscriber
declare @ReportingDate date = getdate();
declare @weekStartDate date = dateadd(week, datediff(week, 0, @ReportingDate),0)
declare @WeekEndDate date = dateadd(day, 6, @weekStartDate)

select
	cs.First_Name,
	cs.Last_Name,
	cs.Cell_Phone_Number,
	sum(usage_event_revenue) as Total_Revenue,
	sum(case when usage_event_type_id = 9 then 1 else 0 end) as Total_SMS_Count,
	sum(case when usage_event_type_id = 7 then 1 else 0 end) as Total_Voice_Call_Count,
	convert(varchar(8),@ReportingDate, 112) as Reporting_Date,
	convert(varchar(8),@WeekStartDate, 112) as Week_Start_Date,
	convert(varchar(8),@WeekEndDate, 112) as Week_End_Date
from
	CombinedSubscribers as cs
join
	VMobile_usage_records as ur on cs.Cell_Phone_Number = MSISDN
where
	cs.Is_Master_Record = 1
group by
	cs.First_Name,
	cs.Last_Name,
	cs.Cell_Phone_Number,
	cs.[Location]
having
	sum(usage_event_revenue) >=30


--------------------------------------reports end-------------------------------------

--script for visuals: finding trends
select
	cs.Cell_Phone_Number,
	cs.First_Name,
	cs.Last_Name,
	sum(ur.usage_event_revenue) as Total_Revenue,
	cast(dateadd(week,datediff(week, 0, ur.usage_event_date_time),0) as date) as Week_Start_Date
from
	CombinedSubscribers as cs
join
	VMobile_usage_records as ur on cs.Cell_Phone_Number = ur.MSISDN
where
	cs.Is_Master_Record = 1
group by
	cs.Cell_Phone_Number,
	cs.First_Name,
	cs.Last_Name,
	cast(dateadd(week, datediff(week, 0, ur.usage_event_date_time), 0) as date)
having
	sum(ur.usage_event_revenue) >= 30




---------------------------------city with the most qualifying subscribers visuals-------------------
select
	l.City_Name,
	count(distinct cs.Cell_Phone_Number) as Qualifying_Subscribers_Count,
	cast(dateadd(week, datediff(week,0,ur.usage_event_date_time),0)as date) as Week_Start_Date
from
	CombinedSubscribers as cs
join
	VMobile_usage_records as ur on cs.Cell_Phone_Number = ur.MSISDN
join
	VMobile_city_lookup as l on cs.[Location] = l.CITY_NAME
where 
	cs.Is_Master_Record = 1
group by
	l.CITY_NAME,
	cast(dateadd(week, datediff(week, 0, ur.usage_event_date_time),0) as date)
having
	sum(ur.USAGE_EVENT_REVENUE)>=30

